import { test, expect } from '@playwright/test'
import { HomePage } from 'page-objects/homepage.js'
import { ReportDetailPage } from 'page-objects/reports/report.detail.page.js'
import {
  createLinkedOrganisation,
  updateMigratedOrganisation,
  uploadAndSubmitSummaryLog
} from '../support/apicalls.js'
import { defraIdStub } from '../support/defra-id-stub.js'
import { parseTonnage } from '../support/tonnage.js'
import { createLinkAndLogin } from '../support/login-helper.js'

// PAE-1783 UI regression guard for "Packaging waste received but not exported"
// on an accredited exporter's monthly report.
//
// The figure is, per load, column S (received for export) minus column T
// (exported), a blank T counting as zero and the row clamped at zero. It used to
// be built by discarding any load whose export date fell inside the period, so a
// load carrying an export date but no exported tonnage read as fully exported
// and the figure collapsed to 0.00.
//
// resources/exporter-not-exported.xlsx is generated by
// resources/generate-not-exported-fixture.mjs, which prints the total asserted
// here. Its four loads cover the rule's three arms — nothing exported, partly
// exported, fully exported — and all carry an in-period export date, the shape
// the old calculation discarded, so the figure reads 0.00 before the fix.
//
// All four are received and exported inside the same period, so this total does
// not depend on how a load exported in a later month is treated.
const EXPECTED_TONNAGE_NOT_EXPORTED = 146.68
const YEAR = 2026
const CADENCE = 'monthly'
const PERIOD = 2 // fixture loads are dated February 2026

test.describe('Packaging waste received but not exported — accredited exporter @accreditedNotExported', () => {
  const regNumber = 'E25SR500020912PA'
  const accNumber = 'E-ACC12245PA'

  let organisationDetails
  let migrationResponse

  test.beforeEach(async ({ page }) => {
    organisationDetails = await createLinkedOrganisation([
      {
        material: 'Paper or board (R3)',
        wasteProcessingType: 'Exporter'
      }
    ])

    migrationResponse = await updateMigratedOrganisation(
      organisationDetails.refNo,
      [{ regNumber, accNumber, status: 'approved' }]
    )

    const user = await createLinkAndLogin(
      page,
      organisationDetails.refNo,
      migrationResponse.email
    )

    await uploadAndSubmitSummaryLog(
      organisationDetails.refNo,
      migrationResponse.registrationIds[0],
      defraIdStub.authHeader(user.userId),
      'resources/exporter-not-exported.xlsx'
    )
  })

  test.afterEach(async ({ page }) => {
    const homePage = new HomePage(page)
    await homePage.signOut()
    await expect(page).toHaveTitle(/Signed out/)
  })

  test('reports the unexported remainder of loads received in the period @accreditedNotExportedFigure', async ({
    page
  }) => {
    const reportDetailPage = new ReportDetailPage(page)

    // Go straight to the February period the fixture loads belong to, rather
    // than the first actionable report (whose period is not guaranteed).
    await reportDetailPage.open(
      organisationDetails.refNo,
      migrationResponse.registrationIds[0],
      YEAR,
      CADENCE,
      PERIOD
    )

    // This caption is accredited-only — registered-only exporters use a
    // different one — and asserting it fails fast if the section disappears.
    await expect(
      page.getByText('Total tonnage not exported', { exact: true })
    ).toBeVisible()

    const notExportedText = await reportDetailPage.totalTonnageNotExported()

    expect(parseTonnage(notExportedText)).toEqual(EXPECTED_TONNAGE_NOT_EXPORTED)
  })
})
